from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('login/',views.loginpage,name='login'),
    path('register/',views.register,name='register'),
    path('handleSignup/',views.handleSignup,name='handleSignup'),
    path('handlelogin/',views.handlelogin,name='handlelogin'),
    path('handleLogout/',views.handleLogout,name='handleLogout'),
    path('submit-query/',views.submit_query,name='submit_query'),
    path('forgot_password/',views.forgot_password,name='forgot_password'),
    path('reset_password/',views.reset_password,name='reset_password'),
    path('addmoney/',views.addmoney,name='addmoney'),
    path('addmoney_submission/',views.addmoney_submission,name='addmoney_submission'),
    path('charts/',views.charts,name='charts'),
    path('tables/',views.tables,name='tables'),
    path('expense_edit/<int:id>',views.expense_edit,name='expense_edit'),
    path('expense_edit/', views.expense_edit_latest, name='expense_edit_latest'),
    path('<int:id>/addmoney_update/', views.addmoney_update, name="addmoney_update") ,
    path('expense_delete/<int:id>',views.expense_delete,name='expense_delete'),
    path('profile/',views.profile,name = 'profile'),
    path('expense_month/',views.expense_month, name = 'expense_month'),
    path('stats/',views.stats, name = 'stats'),
    path('expense_week/',views.expense_week, name = 'expense_week'),
    path('weekly/',views.weekly, name = 'weekly'),
    path('check/',views.check,name="check"),
    path('search/',views.search,name="search"),
    path('<int:id>/profile_edit/',views.profile_edit,name="profile_edit"),
    path('<int:id>/profile_update/',views.profile_update,name="profile_update"),
    path('info/',views.info,name="info"),
    path('info_year/',views.info_year,name="info_year"),
    path('layout2/',views.layout2, name='layout2'),
    path('layout3/',views.layout3, name='layout3'),
    path('page1/',views.page1, name='page1'),
    path('page2/',views.page2, name='page2'),
    path('settings/',views.settings, name='settings'),
    path('login_history/',views.login_history, name='login_history'),
    path('export_expenses_csv/', views.export_expenses_csv, name='export_expenses_csv'),
    path('activity/',views.activity, name='activity'),  
    path('notepad/',views.notepad, name='notepad'),
    path('paint/',views.paint, name='paint'),
    path('notepad/save/',views.save_notepad, name='save_notepad'),
    path('paint/save/',views.save_paint, name='save_paint'),
    path('history_delete/<int:id>/', views.tool_history_delete, name='tool_history_delete'),
]