# Generated by Django 3.2.23 on 2023-11-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20231121_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
